export const GET_SERVICES_REQUEST = 'GET_SERVICE_REQUEST';
export const GET_SERVICES_SUCCESS = 'GET_SERVICE_SUCCESS';
export const GET_SERVICES_FAIL = 'GET_SERVICE_FAIL';

export const GET_SERVICE_DETAILS_REQUEST = 'GET_SERVICE_DETAILS_REQUEST';
export const GET_SERVICE_DETAILS_SUCCESS = 'GET_SERVICE_DETAILS_SUCCESS';
export const GET_SERVICE_DETAILS_FAIL = 'GET_SERVICE_DETAILS_FAIL';

export const GET_SERVICE_DETAILS_RESET = 'GET_SERVICE_DETAILS_RESET';